### ISSUE TITLE
Quiz Lv3 Feedback

### ISSUE THREAD

**Issue by udiiin** [putueddy/nxt-level3-quiz#1]
Halo Mas @putueddy, thanks utk submissionnya, jazaakallaah..

Saya ada beberapa feedback:

**1.)**  
Halaman homepage, pada saat awal buka `http://localhost:3000/` sorting artikelnya sudah sesuai.  
Kemudian klik "Popular", sorting artikel sudah sesuai, dan URL berubah menjadi `http://localhost:3000/?sort=popular`.  
Namun pada saat refresh `http://localhost:3000/?sort=popular`, sorting artikel tidak sesuai.

**2.)**  
Penggunaan `setState` masih belum sesuai:  
`setMetadata((last) => last = meta)`, setIsLoading((state) => state = false).

Contoh yg valid: `setState(newValue)`, `setState((prevValue) => prevValue + 1)`, `setState((prevValue) => !prevValue)`.

Sebaiknya tidak memodifikasi nilai `prevValue` seperti pada `last = meta` atau `state = false`.

**3.)**  
Tidak perlu state `[sorting, setSorting]`, bisa memanfaatkan `useRouter`.

**4.)**  
Pada saat pertama kali buka homepage, tombol "New"nya auto terpilih aja mas, sesuai sorting artikel yg diterapkan.

**5.)**  
Link component, dari `<Link href={{ pathname: '/[slug]', query: { slug: item.slug } }}>` bisa dipersimpel langsung saja seperti ini: ``<Link href=`/${item.slug}`>``

**6.)**  
Utk mendapatkan list article pada `getStaticPaths` bisa langsung aja `perPage=99`.  
*Biar kalo artikelnya bertambah, memastikan tercover di static paths.

**7.)**  
Object shorthand 💡  
Code seperti ini: `{ cat: cat, bird: bird }` bisa dipersimpel penulisannya menjadi `{ cat, bird }`

.

Semoga dimudahkan, barokallaahu fiik

**Comment by putueddy** [comment]
Alhamdulillah, senang lihatnya ada banyak feedback, banyak hal baru yang bisa ana pelajari, Mas @udiiin 
Jazakallah khyr
